apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: k8s-infra-apps
    environment: prod
spec:
  project: morichal-ai-prod
  source:
    repoURL: https://github.com/Deploy-Staff/morichal-k8s-infra
    targetRevision: main
    path: apps/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

