apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: morichal-ai-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: morichal-ai-dev
  annotations:
    description: "AppProject for morichal-ai-dev applications"
spec:
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: ''
      kind: 'ResourceQuota'
    - group: ''
      kind: 'LimitRange'
    - group: 'policy'
      kind: 'PodDisruptionBudget'
  roles:
    - name: developers
      description: Read-only access for developers group
      policies:
        - p, proj:morichal-ai-dev:admins, applications, *, morichal-ai-dev/*, allow
        - p, proj:morichal-ai-dev:admins, logs, *, morichal-ai-dev/*, allow
        - p, proj:morichal-ai-dev:admins, exec, *, morichal-ai-dev/*, allow
        - p, proj:morichal-ai-dev:admins, appprojects, *, morichal-ai-dev, allow
      groups:
        - developers
    - name: admins
      description: Full access for admins group
      policies:
        - p, proj:morichal-ai-dev:admins, applications, *, morichal-ai-dev/*, allow
        - p, proj:morichal-ai-dev:admins, logs, *, morichal-ai-dev/*, allow
        - p, proj:morichal-ai-dev:admins, exec, *, morichal-ai-dev/*, allow
        - p, proj:morichal-ai-dev:admins, appprojects, *, morichal-ai-dev, allow
      groups:
        - admins
  syncWindows: []
