apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra-operators
  namespace: argocd
  labels:
    app.kubernetes.io/name: k8s-infra-operators
    environment: staging
spec:
  project: k8s-infra
  source:
    repoURL: https://github.com/Deploy-Staff/morichal-k8s-infra
    targetRevision: main
    path: operators/staging
    directory: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

